version: "3.8"

services:
  web:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    environment:
      NEXTAUTH_URL: http://52.55.154.162:3000
      AUTH_SECRET: bmDodEZuSDknEgbJc6Ho1VIJAct1AfNIDxKkLFI05CE=
      DATABASE_URL: mongodb+srv://parthp022712:WERQ6PCKG0s8sp6b@rolebase-app.gh4jg.mongodb.net/rolebase-app?retryWrites=true&w=majority&appName=rolebase-app

  mongodb:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: {}
